import uuid from "react-native-uuid";
import { Car, FuelEnum, ServiceStatusEnum } from "./types";

export const cars: Car[] = [
  {
    id: uuid.v4(),
    name: "Subaru Forester",
    mileage: 257400,
    fuel: FuelEnum.PETROL,
    altFuel: FuelEnum.GAS,
    refuels: [
      {
        id: uuid.v4(),
        date: new Date(2025, 9, 14),
        unitPrice: 2.30,
        amountOfFuel: 30.54,
        sumPrice: 2.30 * 30.54,
        fuel: FuelEnum.GAS,
        mileage: 257400,
        avgConsumption: (30.54 * 100) / (257400-257250),
        fullyRefueled: true,
        note: 'refuel gas 30,54L',
      },
      {
        id: uuid.v4(),
        date: new Date(2025, 9, 9),
        unitPrice: 2.6,
        amountOfFuel: 20.17,
        sumPrice: 2.6 * 20.17,
        fuel: FuelEnum.GAS,
        mileage: 257250,
        avgConsumption: (20.17 * 100) / (257250-257000),
        fullyRefueled: true,
        note: 'refuel gas 20,17L',
      },
      {
        id: uuid.v4(),
        date: new Date(2025, 9, 3),
        unitPrice: 2.49,
        amountOfFuel: 35,
        sumPrice: 2.49 * 35,
        fuel: FuelEnum.GAS,
        mileage: 257000,
        avgConsumption: (35 * 100) / (257000-256800),
        fullyRefueled: true,
        note: 'refuel gas 25,34L',
      },
      {
        id: uuid.v4(),
        date: new Date(2025, 9, 1),
        unitPrice: 2.72,
        amountOfFuel: 29.45,
        sumPrice: 2.72 * 29.45,
        fuel: FuelEnum.GAS,
        mileage: 256800,
        avgConsumption: null,
        fullyRefueled: true,
        note: '',
      }
    ],
    services: [],
  },
  {
    id: uuid.v4(),
    name: "Opel Astra H",
    mileage: 292456,
    fuel: FuelEnum.PETROL,
    altFuel: FuelEnum.GAS,
    refuels: [
      {
        id: uuid.v4(),
        date: new Date(2025, 9, 1),
        unitPrice: 5.54,
        amountOfFuel: 30.54,
        sumPrice: 5.54 * 30.54,
        fuel: FuelEnum.GAS,
        mileage: 291680,
        avgConsumption: null,
        fullyRefueled: true,
        note: 'refuel gas 30,54L',
      },
      {
        id: uuid.v4(),
        date: new Date(2025, 9, 14),
        unitPrice: 5.8,
        amountOfFuel: 20.17,
        sumPrice: 5.8 * 20.17,
        fuel: FuelEnum.PETROL,
        mileage: 292456,
        avgConsumption: null,
        fullyRefueled: true,
        note: 'refuel gas 20,17L',
      },
      {
        id: uuid.v4(),
        date: new Date(2025, 9, 3),
        unitPrice: 5.8,
        amountOfFuel: 25.34,
        sumPrice: 5.8 * 25.34,
        fuel: FuelEnum.GAS,
        mileage: 291900,
        avgConsumption: null,
        fullyRefueled: false,
        note: 'refuel gas 25,34L',
      },
      {
        id: uuid.v4(),
        date: new Date(2025, 9, 9),
        unitPrice: 5.72,
        amountOfFuel: 37.29,
        sumPrice: 5.72 * 37.29,
        fuel: FuelEnum.PETROL,
        mileage: 292250,
        avgConsumption: null,
        fullyRefueled: false,
        note: '',
      }
    ],
    services: [],
  },
  {
    id: uuid.v4(),
    name: "Honda CR-V",
    mileage: 246000,
    fuel: FuelEnum.PETROL,
    altFuel: FuelEnum.GAS,
    refuels: [],
    services: [
      {
        id: uuid.v4(),
        createdDate: new Date(2025, 9, 2),
        status: ServiceStatusEnum.PLANNED,
        description: 'Replacement of pads',
        mileage: 235400,
        price: 800.49,
        note: ''
      },
      {
        id: uuid.v4(),
        createdDate: new Date(2025, 9, 14),
        status: ServiceStatusEnum.SCHEDULDED,
        description: 'Timing belt replacement',
        price: 1250,
        note: ''
      },
      {
        id: uuid.v4(),
        createdDate: new Date(2025, 9, 7),
        status: ServiceStatusEnum.COMPLETED,
        description: 'Bodywork repair of the right front fender.',
        mileage: 240000,
        price: 360.99,
        note: 'Very fast, good mechanik, ul. Fatimska 10.'
      },
    ],
  }
];
